In [2]:
student_name = "Jane Doe"
age = 25
is_enrolled = True
gpa = 4.3

In [3]:
print(f" Student: {student_name} ")
print(f" Age: {age} | GPA: {gpa} | Enrolled: {is_enrolled}")

 Student: Jane Doe
 Age: 25 | GPA: 4.3 | Enrolled: True

### **Basic Data Types**

In [4]:
int_val = 56
float_val = 32.01

In [5]:
print(f" Type: {type(int_val)}, {type(float_val)}")

 Type: <class 'int'>, <class 'float'>

#### **Alternatively**

In [6]:
type(int_val)

int

In [7]:
type(float_val)

float

#### **String Type**

In [8]:
str_val = "Volkswagen"
str_val

'Volkswagen'

In [9]:
print(f" Type: {type(str_val)}")
type(str_val)

 Type: <class 'str'>

str

#### **Boolean Type**

In [10]:
Enrollment = True
Passed = False

In [11]:
Enrollment

True

In [12]:
Passed

False

In [14]:
print(f" Types: {type(Enrollment)}, {type(Passed)}")

 Types: <class 'bool'>, <class 'bool'>

#### **Converson of Data Types**

In [15]:
x = "300"
y = int(x)
z = float(y)
w = str(z)

print(f"Types: {type(x)}, {type(y)}, {type(z)}, {type(w)}")

Types: <class 'str'>, <class 'int'>, <class 'float'>, <class 'str'>

#### **Mathematical Operations**

In [17]:
a, b = 20, 9
print('='*60)
print("ARITHMETIC OPERATIONS")
print('='*60)
print(f"Add: {a+b} | Sub: {a-b} | Mul: {a*b}")

============================================================
ARITHMETIC OPERATIONS
============================================================
Add: 29 | Sub: 11 | Mul: 180

In [18]:
print('='*60)
print("ADVANCED OPERATIONS")
print('='*60)
print(f"Div: {a/b} | Floor: {a//b} | Mod: {a%b} | Power: {a**2}")

============================================================
ADVANCED OPERATIONS
============================================================
Div: 2.2222222222222223 | Floor: 2 | Mod: 2 | Power: 400

#### **Logical Operators**

In [19]:
score = 62
score

62

In [20]:
## Conditional logic
if score >= 70:
    grade = "A"
elif score >= 60:
    grade = "B"
elif score >= 50:
    grade = "C"
elif score >= 40:
    grade = "D"
else:
    grade = "Fail"

In [21]:
print(f"Score: {score}, Grade: {grade}")

Score: 62, Grade: B

#### **Dictionaries**

In [28]:
student = {
    "Name": ["Joan", "Sharon", "Ignatius"],
    "Gender": ["Female", "Female", "Male"],
    "Age": [27, 26, 16],
    "Course": ["Data Science", "Marketing", "Software Engineering"]
}

In [29]:
student

{'Name': ['Joan', 'Sharon', 'Ignatius'],
 'Gender': ['Female', 'Female', 'Male'],
 'Age': [27, 26, 16],
 'Course': ['Data Science', 'Marketing', 'Software Engineering']}

#### **Data Frames**

In [33]:
#Install required libraries
#!pip install pandas
#!pip install numpy

In [34]:
# loadding the required libraries

import pandas as pd  ### For data frame manipulation
import numpy as np   ### For numeric manipulation

In [35]:
df = pd.DataFrame(student)
df.head()

       Name  Gender  Age                Course
0      Joan  Female   27          Data Science
1    Sharon  Female   26             Marketing
2  Ignatius    Male   16  Software Engineering

In [36]:
# Exporting to directory
df.to_csv("Student_information.csv", index = False)
print("Created File Successfully!!")

Created File Successfully!!

In [37]:
df2 = pd.read_csv("Student_information.csv")
df2.head()

       Name  Gender  Age                Course
0      Joan  Female   27          Data Science
1    Sharon  Female   26             Marketing
2  Ignatius    Male   16  Software Engineering