## **Data Importation, Cleaning and Wrangling**

### **1. Data Importation**

In [1]:
#!pip install matplotlib
#!pip install seaborn

In [2]:
import pandas as pd              ## For data importation and handling data frames
import numpy as np               ## For numeric operations
import matplotlib.pyplot as plt  ## For data visualization
import seaborn as sn             ## For data visualization

### Filter warnings
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Reading the dataset into Jupyter Notebook

df = pd.read_csv("GSSsubset1.csv")

### **2. General Data Inspection**

In [4]:
# 1. Check column names

print(f" Columns: {df.columns.tolist()}")

 Columns: ['id', 'sex', 'degree', 'income', 'marital', 'age', 'height', 'weight', 'hrswrk']

In [5]:
# 2. Check the shape of the data (x,y) x = observations , y = columns

print(f"Shape: {df.shape}")

Shape: (3000, 9)

In [6]:
# 3. Check the variable types

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   str
 2   degree   2942 non-null   str
 3   income   2767 non-null   float64
 4   marital  2934 non-null   str
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   2879 non-null   float64
 8   hrswrk   2933 non-null   float64
dtypes: float64(4), int64(2), str(3)
memory usage: 211.1 KB

In [7]:
# 4. Check the first few observations

df.head(20)

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18,73.2,86.3,35.0
1,2,MALE,NaN,36544.91,MARRIED,35,69.9,95.3,47.0
2,3,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28,70.1,60.9,16.0
3,4,FEMALE,GRADUATE,NaN,MARRIED,43,61.9,76.0,44.0
4,5,MALE,HIGH SCHOOL,48899.47,MARRIED,48,65.8,58.9,44.0
5,6,FEMALE,HIGH SCHOOL,47790.38,MARRIED,43,60.7,68.4,46.0
6,7,FEMALE,BACHELOR,102903.23,MARRIED,42,66.5,66.7,51.0
7,8,MALE,HIGH SCHOOL,36707.09,NEVER MARRIED,52,65.9,76.8,48.0
8,9,FEMALE,BACHELOR,48404.51,MARRIED,35,66.8,94.6,28.0
9,10,MALE,HIGH SCHOOL,29044.70,NEVER MARRIED,18,69.3,85.2,NaN
10,11,FEMALE,GRADUATE,419380.86,SEPARATED,58,62.4,64.8,31.0
11,12,MALE,JUNIOR COLLEGE,14995.63,WIDOWED,40,66.8,68.7,45.0
12,13,FEMALE,LT HIGH SCHOOL,22832.15,WIDOWED,52,61.3,61.0,25.0
13,14,MALE,LT HIGH SCHOOL,23183.92,NaN,50,71.6,100.4,55.0
14,15,FEMALE,GRADUATE,114886.28,MARRIED,40,64.1,75.5,42.0
15,16,FEMALE,BACHELOR,59232.59,MARRIED,51,62.9,72.9,20.0
16,17,MALE,BACHELOR,NaN,NEVER MARRIED,24,69.3,84.9,50.0
17,18,FEMALE,HIGH SCHOOL,37509.86,SEPARATED,49,61.5,58.8,31.0
18,19,FEMALE,LT HIGH SCHOOL,20512.23,WIDOWED,60,59.0,62.9,22.0
19,20,FEMALE,BACHELOR,84696.68,DIVORCED,63,59.7,65.5,42.0

In [8]:
# 5. Check the last few observations

df.tail(20)

,id,sex,degree,income,marital,age,height,weight,hrswrk
2980,2981,MALE,HIGH SCHOOL,NaN,NEVER MARRIED,47,60.7,61.2,12.0
2981,2982,FEMALE,HIGH SCHOOL,38239.11,MARRIED,43,66.7,64.3,49.0
2982,2983,MALE,HIGH SCHOOL,79377.52,MARRIED,43,69.5,93.4,50.0
2983,2984,MALE,HIGH SCHOOL,25025.96,NEVER MARRIED,41,67.0,76.7,56.0
2984,2985,MALE,LT HIGH SCHOOL,31093.78,DIVORCED,32,70.6,93.8,35.0
2985,2986,FEMALE,BACHELOR,NaN,MARRIED,37,63.6,65.1,43.0
2986,2987,FEMALE,HIGH SCHOOL,55287.09,MARRIED,52,63.7,70.3,42.0
2987,2988,MALE,HIGH SCHOOL,40474.19,MARRIED,33,70.1,73.4,18.0
2988,2989,MALE,LT HIGH SCHOOL,17978.77,NEVER MARRIED,18,70.0,87.1,39.0
2989,2990,MALE,HIGH SCHOOL,80625.90,MARRIED,63,67.8,81.2,45.0
2990,2991,FEMALE,BACHELOR,47934.48,MARRIED,42,64.6,62.9,36.0
2991,2992,MALE,HIGH SCHOOL,NaN,MARRIED,53,70.0,83.7,46.0
2992,2993,MALE,GRADUATE,308066.05,MARRIED,37,68.6,92.4,61.0
2993,2994,MALE,HIGH SCHOOL,NaN,MARRIED,58,66.5,86.3,35.0
2994,2995,FEMALE,HIGH SCHOOL,69153.23,DIVORCED,49,62.1,59.7,39.0
2995,2996,MALE,HIGH SCHOOL,42319.59,MARRIED,60,69.3,85.8,51.0
2996,2997,MALE,GRADUATE,175090.66,MARRIED,57,69.7,98.5,51.0
2997,2998,FEMALE,LT HIGH SCHOOL,12813.84,WIDOWED,51,62.2,62.8,42.0
2998,2999,FEMALE,GRADUATE,61419.36,NEVER MARRIED,18,61.2,60.4,48.0
2999,3000,FEMALE,HIGH SCHOOL,78015.07,MARRIED,33,66.3,72.8,8.0

#### **General Descriptive Statistics**

In [9]:
df.describe()

,id,income,age,height,weight,hrswrk
count,3000.000000,2767.000000,3000.000000,3000.000000,2879.000000,2933.000000
mean,1500.500000,63871.815790,42.078000,67.400500,76.389232,39.778043
std,866.169729,51634.075898,13.314316,3.641297,14.584233,12.594723
min,1.000000,3720.040000,18.000000,58.100000,45.000000,0.000000
25%,750.750000,31989.025000,33.000000,64.600000,65.800000,34.000000
50%,1500.500000,49586.540000,42.000000,67.200000,75.700000,41.000000
75%,2250.250000,78986.595000,51.000000,70.100000,85.700000,48.000000
max,3000.000000,609741.180000,80.000000,78.600000,120.000000,79.000000

In [10]:
# Remove the ID column from the summary
df.drop(columns = ["id"]).describe()

              income          age       height       weight       hrswrk
count    2767.000000  3000.000000  3000.000000  2879.000000  2933.000000
mean    63871.815790    42.078000    67.400500    76.389232    39.778043
std     51634.075898    13.314316     3.641297    14.584233    12.594723
min      3720.040000    18.000000    58.100000    45.000000     0.000000
25%     31989.025000    33.000000    64.600000    65.800000    34.000000
50%     49586.540000    42.000000    67.200000    75.700000    41.000000
75%     78986.595000    51.000000    70.100000    85.700000    48.000000
max    609741.180000    80.000000    78.600000   120.000000    79.000000

#### **General Frequency Table**

In [11]:
print("="*100)
print("Gender Distribution in the General Social Survey")
print("="*100)

df["sex"].value_counts()     # use [] when referencing column

====================================================================================================
Gender Distribution in the General Social Survey
====================================================================================================

sex
FEMALE    1563
MALE      1437
Name: count, dtype: int64

In [12]:
print("="*100)
print("Education Qualification in the General Social Survey")
print("="*100)

df["degree"].value_counts()

====================================================================================================
Education Qualification in the General Social Survey
====================================================================================================

degree
HIGH SCHOOL       1094
LT HIGH SCHOOL     583
BACHELOR           566
JUNIOR COLLEGE     465
GRADUATE           234
Name: count, dtype: int64

In [13]:
print("="*100)
print("Marital Status Distribution in the General Social Survey")
print("="*100)

df["marital"].value_counts()

====================================================================================================
Marital Status Distribution in the General Social Survey
====================================================================================================

marital
MARRIED          1518
NEVER MARRIED     691
DIVORCED          382
WIDOWED           227
SEPARATED         116
Name: count, dtype: int64

### **3. Data Cleaning**

#### **Handling Missing Values**

In [14]:
df.head(20)

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18,73.2,86.3,35.0
1,2,MALE,NaN,36544.91,MARRIED,35,69.9,95.3,47.0
2,3,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28,70.1,60.9,16.0
3,4,FEMALE,GRADUATE,NaN,MARRIED,43,61.9,76.0,44.0
4,5,MALE,HIGH SCHOOL,48899.47,MARRIED,48,65.8,58.9,44.0
5,6,FEMALE,HIGH SCHOOL,47790.38,MARRIED,43,60.7,68.4,46.0
6,7,FEMALE,BACHELOR,102903.23,MARRIED,42,66.5,66.7,51.0
7,8,MALE,HIGH SCHOOL,36707.09,NEVER MARRIED,52,65.9,76.8,48.0
8,9,FEMALE,BACHELOR,48404.51,MARRIED,35,66.8,94.6,28.0
9,10,MALE,HIGH SCHOOL,29044.70,NEVER MARRIED,18,69.3,85.2,NaN
10,11,FEMALE,GRADUATE,419380.86,SEPARATED,58,62.4,64.8,31.0
11,12,MALE,JUNIOR COLLEGE,14995.63,WIDOWED,40,66.8,68.7,45.0
12,13,FEMALE,LT HIGH SCHOOL,22832.15,WIDOWED,52,61.3,61.0,25.0
13,14,MALE,LT HIGH SCHOOL,23183.92,NaN,50,71.6,100.4,55.0
14,15,FEMALE,GRADUATE,114886.28,MARRIED,40,64.1,75.5,42.0
15,16,FEMALE,BACHELOR,59232.59,MARRIED,51,62.9,72.9,20.0
16,17,MALE,BACHELOR,NaN,NEVER MARRIED,24,69.3,84.9,50.0
17,18,FEMALE,HIGH SCHOOL,37509.86,SEPARATED,49,61.5,58.8,31.0
18,19,FEMALE,LT HIGH SCHOOL,20512.23,WIDOWED,60,59.0,62.9,22.0
19,20,FEMALE,BACHELOR,84696.68,DIVORCED,63,59.7,65.5,42.0

In [15]:
# Check the presence of missing values

print("="*100)
print("Checking the Presence of Missing Values in the General Social Survey")
print("="*100)

print(df.isna().sum())

====================================================================================================
Checking the Presence of Missing Values in the General Social Survey
====================================================================================================
id           0
sex          0
degree      58
income     233
marital     66
age          0
height       0
weight     121
hrswrk      67
dtype: int64

In [16]:
# check the percentage of missing values
print("="*100)
print("Checking the Percentage of Missing Values per Variable in the General Social Survey")
print("="*100)

Missing_values = df.isna().mean()
Missing_values

====================================================================================================
Checking the Percentage of Missing Values per Variable in the General Social Survey
====================================================================================================

id         0.000000
sex        0.000000
degree     0.019333
income     0.077667
marital    0.022000
age        0.000000
height     0.000000
weight     0.040333
hrswrk     0.022333
dtype: float64

##### **Complete Cases Analysis(Row Deletion)**

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   str
 2   degree   2942 non-null   str
 3   income   2767 non-null   float64
 4   marital  2934 non-null   str
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   2879 non-null   float64
 8   hrswrk   2933 non-null   float64
dtypes: float64(4), int64(2), str(3)
memory usage: 211.1 KB

In [18]:
df_drop_all = df.dropna()
print(df_drop_all.isna().sum())

id         0
sex        0
degree     0
income     0
marital    0
age        0
height     0
weight     0
hrswrk     0
dtype: int64

In [19]:
df_drop_all.info()

<class 'pandas.DataFrame'>
Index: 2503 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       2503 non-null   int64
 1   sex      2503 non-null   str
 2   degree   2503 non-null   str
 3   income   2503 non-null   float64
 4   marital  2503 non-null   str
 5   age      2503 non-null   int64
 6   height   2503 non-null   float64
 7   weight   2503 non-null   float64
 8   hrswrk   2503 non-null   float64
dtypes: float64(4), int64(2), str(3)
memory usage: 195.5 KB

##### **Mean-Imputation(for symmetric data)**

In [20]:
# Identify the numeric columns

df_mean = df.copy()
df_mean.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18,73.2,86.3,35.0
1,2,MALE,NaN,36544.91,MARRIED,35,69.9,95.3,47.0
2,3,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28,70.1,60.9,16.0
3,4,FEMALE,GRADUATE,NaN,MARRIED,43,61.9,76.0,44.0
4,5,MALE,HIGH SCHOOL,48899.47,MARRIED,48,65.8,58.9,44.0

In [21]:
df_mean.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   str
 2   degree   2942 non-null   str
 3   income   2767 non-null   float64
 4   marital  2934 non-null   str
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   2879 non-null   float64
 8   hrswrk   2933 non-null   float64
dtypes: float64(4), int64(2), str(3)
memory usage: 211.1 KB

In [22]:
numeric_cols = df.select_dtypes(include = "number").columns
df_mean[numeric_cols] = df_mean[numeric_cols].fillna(df_mean[numeric_cols].mean())

In [23]:
print(df.isna().sum())

id           0
sex          0
degree      58
income     233
marital     66
age          0
height       0
weight     121
hrswrk      67
dtype: int64

In [24]:
print(df_mean.isna().sum())

id          0
sex         0
degree     58
income      0
marital    66
age         0
height      0
weight      0
hrswrk      0
dtype: int64

##### **Mean imputation for assymetric data**

In [25]:
df_median = df.copy()
df_median.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18,73.2,86.3,35.0
1,2,MALE,NaN,36544.91,MARRIED,35,69.9,95.3,47.0
2,3,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28,70.1,60.9,16.0
3,4,FEMALE,GRADUATE,NaN,MARRIED,43,61.9,76.0,44.0
4,5,MALE,HIGH SCHOOL,48899.47,MARRIED,48,65.8,58.9,44.0

In [26]:
numeric_cols = df_median.select_dtypes(include = "number").columns
df_median[numeric_cols] = df_median[numeric_cols].fillna(df_median[numeric_cols].median())

In [27]:
print(df_median.isna().sum())

id          0
sex         0
degree     58
income      0
marital    66
age         0
height      0
weight      0
hrswrk      0
dtype: int64

##### **Mode Imputation**

In [28]:
df["degree"].value_counts()

degree
HIGH SCHOOL       1094
LT HIGH SCHOOL     583
BACHELOR           566
JUNIOR COLLEGE     465
GRADUATE           234
Name: count, dtype: int64

In [29]:
df["sex"].value_counts()

sex
FEMALE    1563
MALE      1437
Name: count, dtype: int64

In [30]:
df["marital"].value_counts()

marital
MARRIED          1518
NEVER MARRIED     691
DIVORCED          382
WIDOWED           227
SEPARATED         116
Name: count, dtype: int64

In [31]:
cat_cols = df.select_dtypes(include = ["object", "category"]).columns  # object rep string
for col in cat_cols:                                                   # checks each column
    mode_val = df[col].mode()                                          # returning mode in a column
    if not mode_val.empty:                                             # prevent error if mode doesn't exist
        df[col]= df[col].fillna(mode_val[0])                           # fill NaN with mode

In [32]:
df.isna().sum()   # count number of missing values after imputation

id           0
sex          0
degree       0
income     233
marital      0
age          0
height       0
weight     121
hrswrk      67
dtype: int64

In [33]:
df["degree"].value_counts()

degree
HIGH SCHOOL       1152
LT HIGH SCHOOL     583
BACHELOR           566
JUNIOR COLLEGE     465
GRADUATE           234
Name: count, dtype: int64

In [34]:
numeric_cols = df.select_dtypes(include = "number").columns          # selects columns with numeric data types and returns them
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())  # calculates mean of each column and replaces Nan with mean

In [35]:
## Check presence of missing values

df.isna().sum()

id         0
sex        0
degree     0
income     0
marital    0
age        0
height     0
weight     0
hrswrk     0
dtype: int64

In [36]:
# Check data structure
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   str
 2   degree   3000 non-null   str
 3   income   3000 non-null   float64
 4   marital  3000 non-null   str
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   3000 non-null   float64
 8   hrswrk   3000 non-null   float64
dtypes: float64(4), int64(2), str(3)
memory usage: 211.1 KB

#### **Checking Duplicate Entries**

In [37]:
dup_rows = df.duplicated().sum()
print(dup_rows)

0

In [38]:
# Dropping duplicate rows if they exist

clean_df = df.drop_duplicates()
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   str
 2   degree   3000 non-null   str
 3   income   3000 non-null   float64
 4   marital  3000 non-null   str
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   3000 non-null   float64
 8   hrswrk   3000 non-null   float64
dtypes: float64(4), int64(2), str(3)
memory usage: 211.1 KB

### **4. Handling Outliers**

##### **Outliers are values that lie abnormally very low or very high (far off the trend)**

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   str
 2   degree   3000 non-null   str
 3   income   3000 non-null   float64
 4   marital  3000 non-null   str
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   3000 non-null   float64
 8   hrswrk   3000 non-null   float64
dtypes: float64(4), int64(2), str(3)
memory usage: 211.1 KB

In [45]:
# Check the presence of outliers

numeric_cols = df.select_dtypes(include = ["float64","int64"]).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    
    print(f"Columns '{col}': {len(outliers)} Outliers")

Columns 'id': 0 Outliers
Columns 'income': 201 Outliers
Columns 'age': 10 Outliers
Columns 'height': 2 Outliers
Columns 'weight': 32 Outliers
Columns 'hrswrk': 155 Outliers

In [47]:
numeric_cols = ["income", "age", "height", "weight", "hrswrk"]
outlier_id = {}                                                #creating a dictionary
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    outlier_id[col] = outliers["id"].tolist()

    print(f"Columns '{col}' : {len(outliers)} outliers")         # printing out columns with outliers and their number
    print(outliers["id"].tolist())
    print("="*100)

Columns 'income' : 201 outliers
[11, 36, 38, 73, 76, 87, 88, 102, 111, 112, 144, 146, 174, 200, 206, 211, 223, 227, 244, 275, 286, 289, 306, 326, 352, 359, 375, 381, 397, 404, 437, 455, 460, 493, 505, 519, 523, 536, 544, 549, 568, 591, 596, 603, 608, 660, 668, 727, 730, 731, 732, 761, 767, 786, 797, 808, 834, 840, 847, 913, 923, 931, 946, 975, 976, 981, 984, 1003, 1034, 1054, 1061, 1082, 1087, 1093, 1108, 1127, 1128, 1134, 1149, 1163, 1189, 1242, 1250, 1310, 1344, 1407, 1414, 1418, 1461, 1489, 1506, 1573, 1575, 1598, 1609, 1627, 1638, 1659, 1676, 1677, 1681, 1685, 1691, 1694, 1696, 1710, 1711, 1717, 1731, 1760, 1762, 1770, 1805, 1806, 1814, 1819, 1867, 1870, 1873, 1886, 1888, 1916, 1943, 1953, 1961, 1965, 2018, 2019, 2030, 2042, 2075, 2088, 2107, 2120, 2148, 2149, 2153, 2170, 2181, 2228, 2246, 2254, 2265, 2268, 2281, 2285, 2287, 2292, 2295, 2325, 2336, 2374, 2397, 2414, 2462, 2473, 2475, 2480, 2486, 2498, 2527, 2531, 2539, 2550, 2579, 2590, 2607, 2617, 2627, 2633, 2634, 2644, 2645, 2696, 2701, 2708, 2716, 2728, 2732, 2760, 2769, 2785, 2789, 2801, 2802, 2809, 2820, 2828, 2830, 2844, 2858, 2864, 2880, 2896, 2897, 2933, 2948, 2954, 2979, 2993, 2997]
====================================================================================================
Columns 'age' : 10 outliers
[1254, 1550, 1555, 1717, 1959, 2094, 2242, 2327, 2734, 2838]
====================================================================================================
Columns 'height' : 2 outliers
[257, 431]
====================================================================================================
Columns 'weight' : 32 outliers
[202, 222, 279, 326, 382, 451, 522, 523, 683, 708, 820, 958, 998, 1083, 1374, 1430, 1556, 1600, 1640, 1681, 1742, 1958, 2015, 2219, 2234, 2235, 2396, 2462, 2575, 2842, 2870, 2898]
====================================================================================================
Columns 'hrswrk' : 155 outliers
[39, 56, 63, 67, 72, 73, 106, 107, 115, 124, 208, 246, 250, 260, 278, 282, 305, 322, 378, 385, 387, 424, 426, 433, 437, 469, 479, 506, 535, 581, 585, 600, 602, 622, 658, 672, 694, 734, 736, 777, 780, 823, 848, 865, 936, 983, 996, 1029, 1057, 1087, 1129, 1150, 1194, 1196, 1197, 1223, 1229, 1248, 1274, 1287, 1302, 1305, 1316, 1335, 1345, 1350, 1386, 1388, 1406, 1426, 1429, 1439, 1450, 1466, 1568, 1571, 1585, 1612, 1624, 1627, 1682, 1731, 1739, 1742, 1756, 1762, 1769, 1790, 1792, 1799, 1803, 1819, 1822, 1832, 1879, 1884, 1891, 1894, 1898, 1902, 1944, 1992, 2019, 2071, 2130, 2178, 2237, 2239, 2265, 2272, 2300, 2317, 2333, 2337, 2343, 2352, 2370, 2413, 2419, 2448, 2470, 2505, 2522, 2524, 2532, 2534, 2538, 2549, 2550, 2555, 2568, 2569, 2607, 2629, 2640, 2649, 2664, 2684, 2685, 2689, 2707, 2721, 2732, 2748, 2796, 2851, 2854, 2901, 2917, 2946, 2951, 2958, 2968, 2981, 3000]
====================================================================================================

In [48]:
# cap outliers

numeric_cols = df.select_dtypes(include = ["float64","int64"]).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR

    df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
    df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])

In [49]:
numeric_cols = df.select_dtypes(include = ["float64","int64"]).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    
    print(f"Columns '{col}': {len(outliers)} Outliers")

Columns 'id': 0 Outliers
Columns 'income': 0 Outliers
Columns 'age': 0 Outliers
Columns 'height': 0 Outliers
Columns 'weight': 0 Outliers
Columns 'hrswrk': 0 Outliers

In [51]:
# Check data after cleaning
df.head(10)

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1.0,MALE,HIGH SCHOOL,26722.56000,NEVER MARRIED,18.0,73.2,86.3,35.000000
1,2.0,MALE,HIGH SCHOOL,36544.91000,MARRIED,35.0,69.9,95.3,47.000000
2,3.0,FEMALE,HIGH SCHOOL,59587.14000,DIVORCED,28.0,70.1,60.9,16.000000
3,4.0,FEMALE,GRADUATE,63871.81579,MARRIED,43.0,61.9,76.0,44.000000
4,5.0,MALE,HIGH SCHOOL,48899.47000,MARRIED,48.0,65.8,58.9,44.000000
5,6.0,FEMALE,HIGH SCHOOL,47790.38000,MARRIED,43.0,60.7,68.4,46.000000
6,7.0,FEMALE,BACHELOR,102903.23000,MARRIED,42.0,66.5,66.7,51.000000
7,8.0,MALE,HIGH SCHOOL,36707.09000,NEVER MARRIED,52.0,65.9,76.8,48.000000
8,9.0,FEMALE,BACHELOR,48404.51000,MARRIED,35.0,66.8,94.6,28.000000
9,10.0,MALE,HIGH SCHOOL,29044.70000,NEVER MARRIED,18.0,69.3,85.2,39.778043

#### **Save data as clean data set**

In [52]:
df.to_csv("Cleaned_gss_data.csv")